name: audit-files-downloader
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20230802.0
  - antlr-python-runtime=4.9.3
  - arrow=1.3.0
  - arrow-cpp=14.0.2
  - attrs=23.2.0
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.27
  - aws-c-io=0.13.11
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - binaryornot=0.4.4
  - blas=1.0
  - bokeh=3.4.1
  - boost-cpp=1.78.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cachetools=5.3.3
  - certifi=2024.2.2
  - chardet=3.0.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - contourpy=1.2.0
  - cookiecutter=2.6.0
  - cytoolz=0.12.2
  - dask=2024.5.0
  - dask-core=2024.5.0
  - dask-expr=1.1.1
  - distributed=2024.5.0
  - dynaconf=3.2.5
  - freetype=2.10.4
  - fsspec=2024.5.0
  - gflags=2.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.5.0
  - graphlib-backport=1.0.3
  - grpc-cpp=1.48.2
  - gtest=1.14.0
  - icu=70.1
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib-resources=6.4.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - jinja2=3.1.4
  - jpeg=9e
  - kedro=0.19.6
  - kedro-datasets=3.0.1
  - krb5=1.20.1
  - lazy_loader=0.4
  - lcms2=2.15
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.7.1
  - libcxx=17.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.4.0
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - mdurl=0.1.2
  - more-itertools=10.2.0
  - msgpack-python=1.0.3
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - omegaconf=2.3.0
  - openjpeg=2.3.0
  - openssl=3.3.0
  - orc=1.7.4
  - packaging=24.0
  - pandas=2.2.1
  - parse=1.20.1
  - partd=1.4.2
  - pillow=10.3.0
  - pip=24.0
  - pluggy=1.5.0
  - pre-commit-hooks=4.6.0
  - psutil=5.9.0
  - pyarrow=14.0.2
  - pyarrow-hotfix=0.6
  - pygments=2.18.0
  - pyproject_hooks=1.1.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-build=1.2.1
  - python-dateutil=2.9.0
  - python-slugify=8.0.4
  - python-tzdata=2023.3
  - pytoolconfig=1.2.5
  - pytz=2024.1
  - pyyaml=6.0.1
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - rich=13.7.1
  - rope=1.13.0
  - ruamel.yaml=0.17.21
  - setuptools=69.5.1
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.2.0
  - sortedcontainers=2.4.0
  - sqlite=3.45.3
  - tblib=3.0.0
  - text-unidecode=1.3
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.3.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.1
  - typing_extensions=4.12.1
  - tzdata=2024a
  - urllib3=2.2.1
  - utf8proc=2.6.1
  - wheel=0.43.0
  - xyzservices=2024.4.0
  - xz=5.4.6
  - yaml=0.2.5
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
